# Generated by Django 5.2.16 on 2026-07-23 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': "FAQ (tez-tez so'raladigan savollar)",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Fotogalereya',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Yangilik toifasi',
                'verbose_name_plural': 'Yangilik toifalari',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration', models.CharField(default='2 yil', max_length=100, verbose_name="O'qish muddati")),
                ('diploma', models.CharField(default="Boshlang'ich professional ta'lim", max_length=255, verbose_name='Diplom turi')),
                ('icon', models.CharField(blank=True, default='mortarboard', max_length=100, verbose_name='Ikonka (bootstrap-icons nomi)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Rasm')),
                ('grant_places', models.PositiveIntegerField(default=0, verbose_name="Grant o'rinlari")),
                ('contract_places', models.PositiveIntegerField(default=0, verbose_name="Kontrakt o'rinlari")),
                ('contract_price', models.CharField(blank=True, max_length=100, verbose_name='Kontrakt summasi')),
                ('language', models.CharField(default="O'zbek tili", max_length=100, verbose_name="O'qish tili")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="O'zbekiston tuman 2-son texnikumi", max_length=255, verbose_name='Texnikum nomi')),
                ('short_name', models.CharField(default='2-son texnikum', max_length=100, verbose_name='Qisqa nom')),
                ('slogan', models.CharField(blank=True, default="O'rta bo'g'in kadrlarni yetishtirish", max_length=255, verbose_name='Shior')),
                ('about_short', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('founded_year', models.CharField(default='1973', max_length=20, verbose_name='Tashkil topgan yil')),
                ('address', models.CharField(default="O'zbekiston tuman, Tuyul MFY, Do'stlarobod qo'rg'oni 102-uy", max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(default='+998 91-154-56-97', max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(default='uzbekistandistrict2ps@gmail.com', max_length=254, verbose_name='E-mail')),
                ('work_hours', models.CharField(default='Dushanba-Shanba, 08:00-17:00', max_length=255, verbose_name='Ish vaqti')),
                ('ministry', models.CharField(default="Oliy ta'lim, fan va innovatsiyalar vazirligi huzuridagi Kasbiy ta'lim agentligi", max_length=255, verbose_name='Vazirlik')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logotip')),
                ('map_embed', models.TextField(blank=True, default='https://www.google.com/maps?q=Uzbekistan&output=embed', verbose_name='Xarita (Google Maps embed URL)')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O.')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('role', models.CharField(choices=[('management', 'Rahbariyat'), ('teacher', "O'qituvchi"), ('staff', 'Xodim')], default='teacher', max_length=20, verbose_name='Turi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, verbose_name="Ma'lumot")),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': "Rahbariyat va o'qituvchilar",
                'ordering': ['role', 'order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Qisqa mazmun')),
                ('body', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chop etilgan sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.newscategory', verbose_name='Toifa')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O.')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('prev_school', models.CharField(blank=True, max_length=255, verbose_name="Oldingi o'quv muassasasi")),
                ('message', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('review', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.program', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Onlayn arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
