# Generated by Django 5.2.16 on 2026-07-24 03:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.models.document_storage, upload_to='documents/', verbose_name='Fayl'),
        ),
    ]
